/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated.preferences'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated.student'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated.teacher'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated.admin.analytics'
import { Route as AuthenticatedAdminApprovalsRouteImport } from './routes/_authenticated.admin.approvals'
import { Route as AuthenticatedAdminBranchesRouteImport } from './routes/_authenticated.admin.branches'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as AuthenticatedAdminDetectionsRouteImport } from './routes/_authenticated.admin.detections'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated.admin.notifications'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated.admin.reports'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated.admin.settings'
import { Route as AuthenticatedDetectionsIdRouteImport } from './routes/_authenticated.detections.$id'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated.student.dashboard'
import { Route as AuthenticatedStudentHistoryRouteImport } from './routes/_authenticated.student.history'
import { Route as AuthenticatedStudentNotificationsRouteImport } from './routes/_authenticated.student.notifications'
import { Route as AuthenticatedStudentProfileRouteImport } from './routes/_authenticated.student.profile'
import { Route as AuthenticatedTeacherAnalyticsRouteImport } from './routes/_authenticated.teacher.analytics'
import { Route as AuthenticatedTeacherApprovalsRouteImport } from './routes/_authenticated.teacher.approvals'
import { Route as AuthenticatedTeacherDashboardRouteImport } from './routes/_authenticated.teacher.dashboard'
import { Route as AuthenticatedTeacherNotificationsRouteImport } from './routes/_authenticated.teacher.notifications'
import { Route as AuthenticatedTeacherProfileRouteImport } from './routes/_authenticated.teacher.profile'
import { Route as AuthenticatedTeacherRecordsRouteImport } from './routes/_authenticated.teacher.records'
import { Route as AuthenticatedAdminStudentsIndexRouteImport } from './routes/_authenticated.admin.students.index'
import { Route as AuthenticatedAdminStudentsIdRouteImport } from './routes/_authenticated.admin.students.$id'
import { Route as AuthenticatedAdminTeachersIndexRouteImport } from './routes/_authenticated.admin.teachers.index'
import { Route as AuthenticatedAdminTeachersIdRouteImport } from './routes/_authenticated.admin.teachers.$id'
import { Route as AuthenticatedTeacherStudentsIndexRouteImport } from './routes/_authenticated.teacher.students.index'
import { Route as AuthenticatedTeacherStudentsIdRouteImport } from './routes/_authenticated.teacher.students.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminApprovalsRoute =
  AuthenticatedAdminApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBranchesRoute =
  AuthenticatedAdminBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDetectionsRoute =
  AuthenticatedAdminDetectionsRouteImport.update({
    id: '/detections',
    path: '/detections',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedDetectionsIdRoute =
  AuthenticatedDetectionsIdRouteImport.update({
    id: '/detections/$id',
    path: '/detections/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentHistoryRoute =
  AuthenticatedStudentHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentNotificationsRoute =
  AuthenticatedStudentNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentProfileRoute =
  AuthenticatedStudentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedTeacherAnalyticsRoute =
  AuthenticatedTeacherAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherApprovalsRoute =
  AuthenticatedTeacherApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherDashboardRoute =
  AuthenticatedTeacherDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherNotificationsRoute =
  AuthenticatedTeacherNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherProfileRoute =
  AuthenticatedTeacherProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherRecordsRoute =
  AuthenticatedTeacherRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedAdminStudentsIndexRoute =
  AuthenticatedAdminStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsIdRoute =
  AuthenticatedAdminStudentsIdRouteImport.update({
    id: '/students/$id',
    path: '/students/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeachersIndexRoute =
  AuthenticatedAdminTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTeachersIdRoute =
  AuthenticatedAdminTeachersIdRouteImport.update({
    id: '/teachers/$id',
    path: '/teachers/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedTeacherStudentsIndexRoute =
  AuthenticatedTeacherStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherStudentsIdRoute =
  AuthenticatedTeacherStudentsIdRouteImport.update({
    id: '/students/$id',
    path: '/students/$id',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/detections': typeof AuthenticatedAdminDetectionsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/detections/$id': typeof AuthenticatedDetectionsIdRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/history': typeof AuthenticatedStudentHistoryRoute
  '/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/teacher/approvals': typeof AuthenticatedTeacherApprovalsRoute
  '/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher/notifications': typeof AuthenticatedTeacherNotificationsRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/teacher/records': typeof AuthenticatedTeacherRecordsRoute
  '/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/admin/teachers/$id': typeof AuthenticatedAdminTeachersIdRoute
  '/teacher/students/$id': typeof AuthenticatedTeacherStudentsIdRoute
  '/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/admin/teachers/': typeof AuthenticatedAdminTeachersIndexRoute
  '/teacher/students/': typeof AuthenticatedTeacherStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/detections': typeof AuthenticatedAdminDetectionsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/detections/$id': typeof AuthenticatedDetectionsIdRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/history': typeof AuthenticatedStudentHistoryRoute
  '/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/student/profile': typeof AuthenticatedStudentProfileRoute
  '/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/teacher/approvals': typeof AuthenticatedTeacherApprovalsRoute
  '/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher/notifications': typeof AuthenticatedTeacherNotificationsRoute
  '/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/teacher/records': typeof AuthenticatedTeacherRecordsRoute
  '/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/admin/teachers/$id': typeof AuthenticatedAdminTeachersIdRoute
  '/teacher/students/$id': typeof AuthenticatedTeacherStudentsIdRoute
  '/admin/students': typeof AuthenticatedAdminStudentsIndexRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersIndexRoute
  '/teacher/students': typeof AuthenticatedTeacherStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/approvals': typeof AuthenticatedAdminApprovalsRoute
  '/_authenticated/admin/branches': typeof AuthenticatedAdminBranchesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/detections': typeof AuthenticatedAdminDetectionsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/detections/$id': typeof AuthenticatedDetectionsIdRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/history': typeof AuthenticatedStudentHistoryRoute
  '/_authenticated/student/notifications': typeof AuthenticatedStudentNotificationsRoute
  '/_authenticated/student/profile': typeof AuthenticatedStudentProfileRoute
  '/_authenticated/teacher/analytics': typeof AuthenticatedTeacherAnalyticsRoute
  '/_authenticated/teacher/approvals': typeof AuthenticatedTeacherApprovalsRoute
  '/_authenticated/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/_authenticated/teacher/notifications': typeof AuthenticatedTeacherNotificationsRoute
  '/_authenticated/teacher/profile': typeof AuthenticatedTeacherProfileRoute
  '/_authenticated/teacher/records': typeof AuthenticatedTeacherRecordsRoute
  '/_authenticated/admin/students/$id': typeof AuthenticatedAdminStudentsIdRoute
  '/_authenticated/admin/teachers/$id': typeof AuthenticatedAdminTeachersIdRoute
  '/_authenticated/teacher/students/$id': typeof AuthenticatedTeacherStudentsIdRoute
  '/_authenticated/admin/students/': typeof AuthenticatedAdminStudentsIndexRoute
  '/_authenticated/admin/teachers/': typeof AuthenticatedAdminTeachersIndexRoute
  '/_authenticated/teacher/students/': typeof AuthenticatedTeacherStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/team'
    | '/technology'
    | '/terms'
    | '/admin'
    | '/preferences'
    | '/profile'
    | '/settings'
    | '/student'
    | '/teacher'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/branches'
    | '/admin/dashboard'
    | '/admin/detections'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/detections/$id'
    | '/student/dashboard'
    | '/student/history'
    | '/student/notifications'
    | '/student/profile'
    | '/teacher/analytics'
    | '/teacher/approvals'
    | '/teacher/dashboard'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/records'
    | '/admin/students/$id'
    | '/admin/teachers/$id'
    | '/teacher/students/$id'
    | '/admin/students/'
    | '/admin/teachers/'
    | '/teacher/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/team'
    | '/technology'
    | '/terms'
    | '/admin'
    | '/preferences'
    | '/profile'
    | '/settings'
    | '/student'
    | '/teacher'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/branches'
    | '/admin/dashboard'
    | '/admin/detections'
    | '/admin/notifications'
    | '/admin/reports'
    | '/admin/settings'
    | '/detections/$id'
    | '/student/dashboard'
    | '/student/history'
    | '/student/notifications'
    | '/student/profile'
    | '/teacher/analytics'
    | '/teacher/approvals'
    | '/teacher/dashboard'
    | '/teacher/notifications'
    | '/teacher/profile'
    | '/teacher/records'
    | '/admin/students/$id'
    | '/admin/teachers/$id'
    | '/teacher/students/$id'
    | '/admin/students'
    | '/admin/teachers'
    | '/teacher/students'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/features'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/team'
    | '/technology'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/preferences'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/student'
    | '/_authenticated/teacher'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/approvals'
    | '/_authenticated/admin/branches'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/detections'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/settings'
    | '/_authenticated/detections/$id'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/history'
    | '/_authenticated/student/notifications'
    | '/_authenticated/student/profile'
    | '/_authenticated/teacher/analytics'
    | '/_authenticated/teacher/approvals'
    | '/_authenticated/teacher/dashboard'
    | '/_authenticated/teacher/notifications'
    | '/_authenticated/teacher/profile'
    | '/_authenticated/teacher/records'
    | '/_authenticated/admin/students/$id'
    | '/_authenticated/admin/teachers/$id'
    | '/_authenticated/teacher/students/$id'
    | '/_authenticated/admin/students/'
    | '/_authenticated/admin/teachers/'
    | '/_authenticated/teacher/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRoute
  TechnologyRoute: typeof TechnologyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/approvals': {
      id: '/_authenticated/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AuthenticatedAdminApprovalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branches': {
      id: '/_authenticated/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AuthenticatedAdminBranchesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/detections': {
      id: '/_authenticated/admin/detections'
      path: '/detections'
      fullPath: '/admin/detections'
      preLoaderRoute: typeof AuthenticatedAdminDetectionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/detections/$id': {
      id: '/_authenticated/detections/$id'
      path: '/detections/$id'
      fullPath: '/detections/$id'
      preLoaderRoute: typeof AuthenticatedDetectionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/history': {
      id: '/_authenticated/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof AuthenticatedStudentHistoryRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/notifications': {
      id: '/_authenticated/student/notifications'
      path: '/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof AuthenticatedStudentNotificationsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/profile': {
      id: '/_authenticated/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof AuthenticatedStudentProfileRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/teacher/analytics': {
      id: '/_authenticated/teacher/analytics'
      path: '/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof AuthenticatedTeacherAnalyticsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/approvals': {
      id: '/_authenticated/teacher/approvals'
      path: '/approvals'
      fullPath: '/teacher/approvals'
      preLoaderRoute: typeof AuthenticatedTeacherApprovalsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/dashboard': {
      id: '/_authenticated/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof AuthenticatedTeacherDashboardRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/notifications': {
      id: '/_authenticated/teacher/notifications'
      path: '/notifications'
      fullPath: '/teacher/notifications'
      preLoaderRoute: typeof AuthenticatedTeacherNotificationsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/profile': {
      id: '/_authenticated/teacher/profile'
      path: '/profile'
      fullPath: '/teacher/profile'
      preLoaderRoute: typeof AuthenticatedTeacherProfileRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/records': {
      id: '/_authenticated/teacher/records'
      path: '/records'
      fullPath: '/teacher/records'
      preLoaderRoute: typeof AuthenticatedTeacherRecordsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/admin/students/': {
      id: '/_authenticated/admin/students/'
      path: '/students'
      fullPath: '/admin/students/'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students/$id': {
      id: '/_authenticated/admin/students/$id'
      path: '/students/$id'
      fullPath: '/admin/students/$id'
      preLoaderRoute: typeof AuthenticatedAdminStudentsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teachers/': {
      id: '/_authenticated/admin/teachers/'
      path: '/teachers'
      fullPath: '/admin/teachers/'
      preLoaderRoute: typeof AuthenticatedAdminTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/teachers/$id': {
      id: '/_authenticated/admin/teachers/$id'
      path: '/teachers/$id'
      fullPath: '/admin/teachers/$id'
      preLoaderRoute: typeof AuthenticatedAdminTeachersIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/teacher/students/': {
      id: '/_authenticated/teacher/students/'
      path: '/students'
      fullPath: '/teacher/students/'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/students/$id': {
      id: '/_authenticated/teacher/students/$id'
      path: '/students/$id'
      fullPath: '/teacher/students/$id'
      preLoaderRoute: typeof AuthenticatedTeacherStudentsIdRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminApprovalsRoute: typeof AuthenticatedAdminApprovalsRoute
  AuthenticatedAdminBranchesRoute: typeof AuthenticatedAdminBranchesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDetectionsRoute: typeof AuthenticatedAdminDetectionsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStudentsIdRoute: typeof AuthenticatedAdminStudentsIdRoute
  AuthenticatedAdminTeachersIdRoute: typeof AuthenticatedAdminTeachersIdRoute
  AuthenticatedAdminStudentsIndexRoute: typeof AuthenticatedAdminStudentsIndexRoute
  AuthenticatedAdminTeachersIndexRoute: typeof AuthenticatedAdminTeachersIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminApprovalsRoute: AuthenticatedAdminApprovalsRoute,
  AuthenticatedAdminBranchesRoute: AuthenticatedAdminBranchesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDetectionsRoute: AuthenticatedAdminDetectionsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStudentsIdRoute: AuthenticatedAdminStudentsIdRoute,
  AuthenticatedAdminTeachersIdRoute: AuthenticatedAdminTeachersIdRoute,
  AuthenticatedAdminStudentsIndexRoute: AuthenticatedAdminStudentsIndexRoute,
  AuthenticatedAdminTeachersIndexRoute: AuthenticatedAdminTeachersIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentHistoryRoute: typeof AuthenticatedStudentHistoryRoute
  AuthenticatedStudentNotificationsRoute: typeof AuthenticatedStudentNotificationsRoute
  AuthenticatedStudentProfileRoute: typeof AuthenticatedStudentProfileRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentHistoryRoute: AuthenticatedStudentHistoryRoute,
  AuthenticatedStudentNotificationsRoute:
    AuthenticatedStudentNotificationsRoute,
  AuthenticatedStudentProfileRoute: AuthenticatedStudentProfileRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherAnalyticsRoute: typeof AuthenticatedTeacherAnalyticsRoute
  AuthenticatedTeacherApprovalsRoute: typeof AuthenticatedTeacherApprovalsRoute
  AuthenticatedTeacherDashboardRoute: typeof AuthenticatedTeacherDashboardRoute
  AuthenticatedTeacherNotificationsRoute: typeof AuthenticatedTeacherNotificationsRoute
  AuthenticatedTeacherProfileRoute: typeof AuthenticatedTeacherProfileRoute
  AuthenticatedTeacherRecordsRoute: typeof AuthenticatedTeacherRecordsRoute
  AuthenticatedTeacherStudentsIdRoute: typeof AuthenticatedTeacherStudentsIdRoute
  AuthenticatedTeacherStudentsIndexRoute: typeof AuthenticatedTeacherStudentsIndexRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherAnalyticsRoute: AuthenticatedTeacherAnalyticsRoute,
  AuthenticatedTeacherApprovalsRoute: AuthenticatedTeacherApprovalsRoute,
  AuthenticatedTeacherDashboardRoute: AuthenticatedTeacherDashboardRoute,
  AuthenticatedTeacherNotificationsRoute:
    AuthenticatedTeacherNotificationsRoute,
  AuthenticatedTeacherProfileRoute: AuthenticatedTeacherProfileRoute,
  AuthenticatedTeacherRecordsRoute: AuthenticatedTeacherRecordsRoute,
  AuthenticatedTeacherStudentsIdRoute: AuthenticatedTeacherStudentsIdRoute,
  AuthenticatedTeacherStudentsIndexRoute:
    AuthenticatedTeacherStudentsIndexRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
  AuthenticatedDetectionsIdRoute: typeof AuthenticatedDetectionsIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
  AuthenticatedDetectionsIdRoute: AuthenticatedDetectionsIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRoute,
  TechnologyRoute: TechnologyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
